### ISSUE TITLE
projects-past.php template

### ISSUE THREAD

**Issue by tfleischauer** [nategunn/itc210-earthship-seattle#57]
Allows both Projects Past and Events Past instead of only Projects Past as intended. This template file does not exclude posts where the Category=Events and Tag=Past.

**Comment by tfleischauer** [comment]
![past-projects---earthship-seattle---seattle--wa](https://cloud.githubusercontent.com/assets/6358117/5631599/9f913bbe-957c-11e4-8564-a2ea280a1a39.jpg)

**Comment by Mattwig** [comment]
On line 20 in the code the   
  <?php if(query_posts( 'cat=projects&tag=past' )): ?> 

the cat refers to the category id not the name if we use

 <?php if(query_posts( 'category_name=projects&tag=past' )): ?> 

It works fine. The problem is that using query posts is bad practice according to the wordpress codex it recommends using a custom WP_Query such as

<?php
		$pastQuery = new WP_Query('category_name=projects&tag=past');
   		while ($pastQuery->have_posts()) : $pastQuery->the_post(); ?>

At least thats what I got from  http://codex.wordpress.org/Function_Reference/query_posts
